<?php

$samples = [
    'auspicious-period' => [
        'image' => '/assets/img/icon/auspicious-period.png',
        'title' => 'Auspicious Period',
        'url' => DEMO_BASE_URL . '/auspicious-period.php',
        'docs' => 'auspicious-period',
    ],
    'chart' => [
        'image' => '/assets/img/icon/chart.png',
        'title' => 'Chart',
        'url' => DEMO_BASE_URL . '/chart.php',
        'docs' => 'birth-chart',
    ],
    'choghadiya' => [
        'image' => '/assets/img/icon/choghadiya.png',
        'title' => 'Choghadiya',
        'url' => DEMO_BASE_URL . '/choghadiya.php',
        'docs' => 'choghadiya',
    ],
    'inauspicious-period' => [
        'image' => '/assets/img/icon/inauspicious-period.png',
        'title' => 'Inauspicious Period',
        'url' => DEMO_BASE_URL . '/inauspicious-period.php',
        'docs' => 'inauspicious-period',
    ],
    'kaal-sarp-dosha' => [
        'image' => '/assets/img/icon/kaalsarp-dosha.png',
        'title' => 'Kaalsarp Dosha',
        'url' => DEMO_BASE_URL . '/kaal-sarp-dosha.php',
        'docs' => 'kaal-sarp-dosha',
    ],
    'kundli' => [
        'image' => '/assets/img/icon/kundli.png',
        'title' => 'Kundli',
        'url' => DEMO_BASE_URL . '/kundli.php',
        'docs' => 'kundli',
    ],
    'kundli-matching' => [
        'image' => '/assets/img/icon/kundli-matching.png',
        'title' => 'Kundli Matching',
        'url' => DEMO_BASE_URL . '/kundli-matching.php',
        'docs' => 'kundli-matching',
    ],
    'mangal-dosha' => [
        'image' => '/assets/img/icon/mangal-dhosha.png',
        'title' => 'Mangal Dosha',
        'url' => DEMO_BASE_URL . '/mangal-dosha.php',
        'docs' => 'mangal-dosha',
    ],
    'birth-details' => [
        'image' => '/assets/img/icon/birthchart.png',
        'title' => 'Birth Details',
        'url' => DEMO_BASE_URL . '/birth-details.php',
        'docs' => 'birth-details',
    ],
    'nakshatra-porutham' => [
        'image' => '/assets/img/icon/nakshatra-porutham.png',
        'title' => 'Nakshatra Porutham',
        'url' => DEMO_BASE_URL . '/nakshatra-porutham.php',
        'docs' => 'nakshatra-porutham',
    ],
    'panchang' => [
        'image' => '/assets/img/icon/panchang.png',
        'title' => 'Panchang',
        'url' => DEMO_BASE_URL . '/panchang.php',
        'docs' => 'panchang',
    ],
    'papasamyam-check' => [
        'image' => '/assets/img/icon/papasamyam-check.png',
        'title' => 'Papasamyam Check',
        'url' => DEMO_BASE_URL . '/papasamyam-check.php',
        'docs' => 'papasamyam-check',
    ],
    'papasamyam' => [
        'image' => '/assets/img/icon/papasamyam.png',
        'title' => 'Papasamyam',
        'url' => DEMO_BASE_URL . '/papasamyam.php',
        'docs' => 'papasamyam',
    ],
    'planet-position' => [
        'image' => '/assets/img/icon/planet-position.png',
        'title' => 'Planet Position',
        'url' => DEMO_BASE_URL . '/planet-position.php',
        'docs' => 'planet-position',
    ],
    'porutham' => [
        'image' => '/assets/img/icon/jathagam-porutham-tamil.png',
        'title' => 'Porutham',
        'url' => DEMO_BASE_URL . '/porutham.php',
        'docs' => 'porutham',
    ],
    'sade-sati' => [
        'image' => '/assets/img/icon/sade-sati.png',
        'title' => 'Sade-Sati',
        'url' => DEMO_BASE_URL . '/sade-sati.php',
        'docs' => 'sade-sati',
    ],
    'thirumana-porutham' => [
        'image' => '/assets/img/icon/thirumana-porutham.png',
        'title' => 'Thirumana Porutham',
        'url' => DEMO_BASE_URL . '/thirumana-porutham.php',
        'docs' => 'thirumana-porutham',
    ],
    'anandadi-yoga' => [
        'image' => '/assets/img/icon/anandadi-yoga.png',
        'title' => 'Anandadi Yoga',
        'url' => DEMO_BASE_URL . '/anandadi-yoga.php',
        'docs' => 'anandadi-yoga',
    ],
    'chandra-bala' => [
        'image' => '/assets/img/icon/chandra-bala.png',
        'title' => 'Chandra Bala',
        'url' => DEMO_BASE_URL . '/chandra-bala.php',
        'docs' => 'chandra-bala',
    ],
    'tara-bala' => [
        'image' => '/assets/img/icon/tara-bala.png',
        'title' => 'Tara Bala',
        'url' => DEMO_BASE_URL . '/tara-bala.php',
        'docs' => 'tara-bala',
    ],
    'ritu' => [
        'image' => '/assets/img/icon/planet-position.png',
        'title' => 'Ritu',
        'url' => DEMO_BASE_URL . '/ritu.php',
        'docs' => 'ritu',
    ],
    'solstice' => [
        'image' => '/assets/img/icon/solstice.png',
        'title' => 'Solstice',
        'url' => DEMO_BASE_URL . '/solstice.php',
        'docs' => 'solstice',
    ],
    'hora' => [
        'image' => '/assets/img/icon/hora.png',
        'title' => 'Hora',
        'url' => DEMO_BASE_URL . '/hora.php',
        'docs' => 'hora',
    ],
    'disha-shool' => [
        'image' => '/assets/img/icon/disha-shool.png',
        'title' => 'Disha Shool',
        'url' => DEMO_BASE_URL . '/disha-shool.php',
        'docs' => 'disha-shool',
    ],
    'auspicious-yoga' => [
        'image' => '/assets/img/icon/panchang.png',
        'title' => 'Auspicious Yoga',
        'url' => DEMO_BASE_URL . '/auspicious-yoga.php',
        'docs' => 'auspicious-yoga',
    ],
    'calendar' => [
        'image' => '/assets/img/icon/calendar.png',
        'title' => 'Calendar',
        'url' => DEMO_BASE_URL . '/calendar.php',
        'docs' => 'calendar',
    ],
    'hindu-panchang' => [
        'image' => '/assets/img/icon/hindu-panchang.png',
        'title' => 'Hindu Panchang',
        'url' => DEMO_BASE_URL . '/hindu-panchang.php',
        'docs' => 'panchang',
    ],
    'tamil-panchang' => [
        'image' => '/assets/img/icon/tamil-panchang.png',
        'title' => 'Tamil Panchang',
        'url' => DEMO_BASE_URL . '/tamil-panchang.php',
        'docs' => 'panchang',
    ],
    'telugu-panchang' => [
        'image' => '/assets/img/icon/telugu-panchang.png',
        'title' => 'Telugu Panchang',
        'url' => DEMO_BASE_URL . '/telugu-panchang.php',
        'docs' => 'panchang',
    ],
    'numerology' => [
        'image' => '/assets/img/icon/numerology.png',
        'title' => 'Numerology',
        'url' => DEMO_BASE_URL . '/numerology.php',
        'docs' => 'numerology',
    ],
    'daily-horoscope' => [
        'image' => '/assets/img/icon/daily-horoscope.png',
        'title' => 'Daily Horoscope',
        'url' => DEMO_BASE_URL . '/daily-horoscope.php',
        'docs' => 'numerology',
    ],
    'dasha-periods' => [
        'image' => '/assets/img/icon/dasha-periods.png',
        'title' => 'Dasha Periods',
        'url' => DEMO_BASE_URL . '/dasha-periods.php',
        'docs' => 'dasha-periods',
    ],
    'horoscope-yoga' => [
        'image' => '/assets/img/icon/panchang.png',
        'title' => 'Horoscope Yoga',
        'url' => DEMO_BASE_URL . '/horoscope-yoga.php',
        'docs' => 'dasha-periods',
    ],
    'pdf-report' => [
        'image' => '/assets/img/icon/panchang.png',
        'title' => 'PDF Report',
        'url' => DEMO_BASE_URL . '/pdf-report.php',
        'docs' => 'pdf-report',
    ]
];
